export type MetricKey =
  | 'instructorPresence'
  | 'responsiveness'
  | 'feedbackQuality'
  | 'policyCompliance'
  | 'studentExperience';

export type Scores = Record<MetricKey, number>;
export type TriggerMap = Record<string, boolean>;

export interface Condition {
  triggerEquals?: Record<string, boolean>;
  all?: Condition[];
  any?: Condition[];
  choiceIn?: string[];
}

export interface Choice {
  id: string;
  text: string;
  effects: Partial<Scores>;
  setTriggers?: Record<string, boolean>;
  feedback: string;
}

export interface ConditionalMessage {
  if: Condition;
  message: string;
}

export interface ConditionalEffect {
  if: Condition;
  additionalEffects: Partial<Scores>;
}

export interface Scene {
  id: string;
  type: 'decision' | 'conditional_decision';
  title: string;
  prompt: string;
  showIf?: Condition;
  choices: Choice[];
  conditionalMessages?: ConditionalMessage[];
  conditionalEffects?: ConditionalEffect[];
}

export interface PhaseEvent {
  id: string;
  if: Condition;
  display: string;
}

export interface CarryForwardItem {
  if: Condition;
  effect: string;
}

export interface Checkpoint {
  title: string;
  showDashboard: boolean;
  showFinalEvaluation?: boolean;
  summaryVariants?: Record<string, string>;
}

export interface Phase {
  id: string;
  title: string;
  goal: string;
  introText: string;
  prePhaseEvents: PhaseEvent[];
  scenes: Scene[];
  checkpoint: Checkpoint;
  carryForward?: CarryForwardItem[];
}

export interface OutcomeDef {
  id: string;
  label: string;
  message: string;
}

export interface SimulationData {
  simulationId: string;
  title: string;
  version: string;
  institution: string;
  description: string;
  engine: {
    scoreRange: { min: number; max: number };
    startingScores: Scores;
    dashboardThresholds: Record<'green' | 'yellow' | 'red', { min: number; max: number }>;
    dashboardDisplay: {
      showAtEndOfEachPhase: boolean;
      showFinalSummary: boolean;
      style: string;
      colors: string[];
      metrics: MetricKey[];
    };
    rules: Record<string, string | boolean>;
  };
  triggers: string[];
  phases: Phase[];
  evaluation: {
    majorPolicyViolationTriggers: string[];
    requiredOnTimeTrigger: string;
    redCategoryThresholdCountForFailure: number;
    outcomes: OutcomeDef[];
    optionalAutoGeneratedSections: { id: string; title: string; rule: string }[];
  };
}

export interface DecisionRecord {
  phaseId: string;
  sceneId: string;
  sceneTitle: string;
  choiceId: string;
  choiceText: string;
  feedback: string;
}

export interface EvaluationResult {
  id: string;
  label: string;
  message: string;
}
